### ISSUE TITLE
Do you solve the problem?

### ISSUE THREAD

**Issue by jxiaox** [naddison36/web3-jest#1]
I just have the same problem yet.

**Comment by takahser** [comment]
+1

**Comment by takahser** [comment]
is there a solution?
I tried https://stackoverflow.com/questions/46672532/error-when-using-web3-js-with-jest but it didn't work for me

**Comment by naddison36** [comment]
No, I don't have a solution. I gave up on web3.js over a year ago in favour of Ethers.js and haven't look back at web3.js since.

**Comment by takahser** [comment]
thanks a lot for the reply, I'm gonna look into Ethers.js as well then 👍🏼
